import fs from "fs"
import path from "path"
import { execSync, spawn } from "child_process"
import { chromium, type BrowserContext, type Page } from "playwright"
import type { BrowserPort, LoggerPort } from "../../domain/ports"
import type { CookieRefreshResult, CookieRefresherConfig } from "../../domain/types"
import { ok, err, type Result } from "../../shared/result"

const BROWSER_INIT_TIMEOUT_MS = 30_000

export const createPlaywrightBrowser = (
  config: CookieRefresherConfig,
  logger: LoggerPort,
): BrowserPort => {
  let browser: BrowserContext | null = null
  let isInitializing = false

  const cookieFile = config.cookieFile || path.join(config.cookieDir, "youtube-cookies.txt")

  fs.mkdirSync(config.cookieDir, { recursive: true, mode: 0o700 })
  fs.mkdirSync(config.browserProfile, { recursive: true, mode: 0o700 })

  const waitForProfileFree = async (timeoutMs = 10000): Promise<void> => {
    const lockFiles = ["SingletonLock", "SingletonCookie", "SingletonSocket"]
    const start = Date.now()

    while (Date.now() - start < timeoutMs) {
      const hasLocks = lockFiles.some(file =>
        fs.existsSync(path.join(config.browserProfile, file))
      )
      if (!hasLocks) return

      for (const file of lockFiles) {
        const lockPath = path.join(config.browserProfile, file)
        try {
          const stat = fs.statSync(lockPath)
          if (Date.now() - stat.mtimeMs > 5000) fs.unlinkSync(lockPath)
        } catch {}
      }
      await new Promise(r => setTimeout(r, 500))
    }

    for (const file of lockFiles) {
      const lockPath = path.join(config.browserProfile, file)
      try { fs.unlinkSync(lockPath) } catch {}
    }
  }

  const initBrowser = async (): Promise<Result<void, string>> => {
    if (browser) return ok(undefined)
    if (isInitializing) {
      const start = Date.now()
      while (isInitializing) {
        if (Date.now() - start > BROWSER_INIT_TIMEOUT_MS) {
          isInitializing = false
          return err("Browser initialization timed out")
        }
        await new Promise(r => setTimeout(r, 500))
      }
      return ok(undefined)
    }

    isInitializing = true
    try {
      await waitForProfileFree()
      browser = await chromium.launchPersistentContext(config.browserProfile, {
        headless: true,
        args: [
          "--disable-blink-features=AutomationControlled",
          "--no-sandbox",
          "--disable-setuid-sandbox",
          "--disable-features=ProcessSingleton",
        ],
      })
      browser.on("close", () => { browser = null })
      return ok(undefined)
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e)
      return err(msg)
    } finally {
      isInitializing = false
    }
  }

  const closeBrowser = async (): Promise<void> => {
    if (browser) {
      await browser.close().catch(() => {})
      browser = null
    }
  }

  const filterYouTubeCookies = (cookies: Awaited<ReturnType<BrowserContext["cookies"]>>): Awaited<ReturnType<BrowserContext["cookies"]>> =>
    cookies.filter(c =>
      c.domain.includes("youtube.com") ||
      c.domain.includes(".google.com") ||
      c.domain.includes(".youtube.com")
    )

  const cookiesToNetscape = (cookies: Array<{ name: string; value: string; domain: string; path: string; secure: boolean; expires: number; httpOnly: boolean }>): string => {
    const lines = ["# Netscape HTTP Cookie File", "# Generated by Playwright", ""]
    for (const c of cookies) {
      const domain = c.domain.startsWith(".") ? c.domain : `.${c.domain}`
      lines.push(`${domain}\tTRUE\t${c.path}\t${c.secure ? "TRUE" : "FALSE"}\t${c.expires > 0 ? Math.floor(c.expires) : 0}\t${c.name}\t${c.value}`)
    }
    return lines.join("\n") + "\n"
  }

  const extractAndWriteCookies = async (): Promise<number> => {
    const cookies = await browser!.cookies()
    const ytCookies = filterYouTubeCookies(cookies).map(c => ({
      ...c, path: c.path || "/", secure: c.secure || false, expires: c.expires || 0, httpOnly: c.httpOnly || false,
    }))
    if (ytCookies.length === 0) throw new Error("No YouTube cookies found")
    const netscape = cookiesToNetscape(ytCookies)
    fs.writeFileSync(cookieFile, netscape, { mode: 0o600 })
    return ytCookies.length
  }

  const refresh = async (): Promise<CookieRefreshResult> => {
    if (!browser) {
      const initResult = await initBrowser()
      if (!initResult.ok) return { success: false, error: initResult.error, timestamp: new Date().toISOString() }
    }
    if (!browser) return { success: false, error: "Browser unavailable", timestamp: new Date().toISOString() }

    let page: Page | null = null
    try {
      page = await browser.newPage()
      try {
        await page.goto("https://www.youtube.com", { waitUntil: "domcontentloaded", timeout: 30000 })
        await page.waitForTimeout(3000)
      } catch (navError: unknown) {
        logger.warn("cookies", "Navigation during cookie refresh failed, extracting cookies anyway", {
          error: navError instanceof Error ? navError.message : String(navError),
        })
      }

      let isLoggedIn = false
      try {
        isLoggedIn = await page.evaluate(() => !!document.querySelector("yt-img-shadow#avatar"))
      } catch {}

      const count = await extractAndWriteCookies()
      return { success: true, cookieCount: count, isLoggedIn, timestamp: new Date().toISOString() }
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e)
      if (msg.includes("closed") || msg.includes("crashed")) browser = null
      return { success: false, error: msg, timestamp: new Date().toISOString() }
    } finally {
      page?.close().catch(() => {})
    }
  }

  const extract = async (): Promise<CookieRefreshResult> => {
    if (!browser) return { success: false, error: "Browser not running", timestamp: new Date().toISOString() }
    try {
      const count = await extractAndWriteCookies()
      return { success: true, cookieCount: count, timestamp: new Date().toISOString() }
    } catch (e: unknown) {
      return { success: false, error: e instanceof Error ? e.message : String(e), timestamp: new Date().toISOString() }
    }
  }

  const setupLogin = async (): Promise<Result<{ url: string; instructions: string }, string>> => {
    try {
      execSync("which Xvfb", { stdio: "ignore" })
    } catch {
      return err("Xvfb is not available")
    }

    if (browser) await closeBrowser()
    await waitForProfileFree()

    const display = ":99"
    const vncPort = process.env.VNC_PORT || "6080"

    const spawnVnc = (label: string, cmd: string, args: string[]): ReturnType<typeof spawn> => {
      const child = spawn(cmd, args, { stdio: "ignore", env: { ...process.env, DISPLAY: display } })
      child.on("error", (e: Error) => logger.error("vnc", `${label} failed to start`, { error: e.message }))
      child.on("exit", (code, signal) => logger.warn("vnc", `${label} exited`, { code, signal }))
      return child
    }

    const xvfb = spawnVnc("Xvfb", "Xvfb", [display, "-screen", "0", "1280x720x24"])
    const x11vnc = spawnVnc("x11vnc", "x11vnc", ["-display", display, "-forever", "-nopw", "-listen", "0.0.0.0", "-rfbport", "5900", "-shared"])
    const websockify = spawnVnc("websockify", "websockify", ["--web", "/usr/share/novnc", vncPort, "localhost:5900"])

    try {
      browser = await chromium.launchPersistentContext(config.browserProfile, {
        headless: false,
        args: ["--disable-blink-features=AutomationControlled", "--no-sandbox", "--disable-setuid-sandbox", "--disable-features=ProcessSingleton"],
        env: { ...process.env, DISPLAY: display },
      })
      const page = await browser.newPage()
      await page.goto("https://www.youtube.com", { waitUntil: "domcontentloaded" })

      browser.on("close", () => {
        browser = null
        xvfb.kill("SIGTERM")
        x11vnc.kill("SIGTERM")
        websockify.kill("SIGTERM")
      })

      const vncUrl = `http://localhost:${vncPort}/vnc.html?autoconnect=true`
      return ok({ url: vncUrl, instructions: `Open ${vncUrl} in your browser. Sign in to YouTube, then use Extract Cookies.` })
    } catch (e: unknown) {
      xvfb.kill("SIGTERM")
      x11vnc.kill("SIGTERM")
      websockify.kill("SIGTERM")
      browser = null
      return err(e instanceof Error ? e.message : String(e))
    }
  }

  const resetProfile = async (): Promise<void> => {
    if (browser) await closeBrowser()
    await waitForProfileFree()
    try { execSync("pkill -9 -f chrome || true", { stdio: "ignore" }) } catch {}
    if (fs.existsSync(config.browserProfile)) {
      const entries = fs.readdirSync(config.browserProfile)
      for (const entry of entries) {
        const fullPath = path.join(config.browserProfile, entry)
        try { fs.rmSync(fullPath, { recursive: true, force: true }) } catch {}
      }
    }
  }

  return {
    init: initBrowser,
    close: closeBrowser,
    refresh,
    extract,
    setupLogin,
    isActive: () => browser !== null,
    resetProfile,
  } as const
}
