const express = require("express")
const { chromium } = require("playwright")
const fs = require("fs")
const path = require("path")
const { spawn } = require("child_process")

const app = express()
app.use(express.json())

const PORT = process.env.PORT || 3001
const VNC_PORT = process.env.VNC_PORT || 6080
const COOKIE_FILE = process.env.COOKIE_FILE || "/cookies/youtube-cookies.txt"
const BROWSER_PROFILE = process.env.BROWSER_PROFILE || "/profile"

let xvfb = null
let noVNC = null
let vncServer = null

// Ensure directories exist
fs.mkdirSync(path.dirname(COOKIE_FILE), { recursive: true })
fs.mkdirSync(BROWSER_PROFILE, { recursive: true })

// ─── Xvfb + noVNC helpers ───

function startVNC() {
  return new Promise((resolve, reject) => {
    // Start Xvfb virtual display
    xvfb = spawn("Xvfb", [":99", "-screen", "0", "1280x720x24"], {
      stdio: "ignore",
      env: { ...process.env, DISPLAY: ":99" },
    })

    xvfb.on("error", (err) => {
      console.error("Xvfb failed to start:", err.message)
      reject(err)
    })

    // Start x11vnc server
    vncServer = spawn("x11vnc", [
      "-display", ":99",
      "-forever",
      "-nopw",
      "-listen", "0.0.0.0",
      "-rfbport", "5900",
      "-shared",
    ], {
      stdio: "ignore",
      env: { ...process.env, DISPLAY: ":99" },
    })

    // Start noVNC websockify
    noVNC = spawn("websockify", [
      "--web", "/usr/share/novnc",
      String(VNC_PORT),
      "localhost:5900",
    ], {
      stdio: "ignore",
      env: { ...process.env, DISPLAY: ":99" },
    })

    // Give it a moment to start
    setTimeout(() => resolve(), 1000)
  })
}

function stopVNC() {
  for (const proc of [noVNC, vncServer, xvfb]) {
    if (proc && !proc.killed) proc.kill("SIGTERM")
  }
  xvfb = null
  noVNC = null
  vncServer = null
}

// ─── Cookie extraction ───

function cookiesToNetscape(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by cookie-refresher",
    "",
  ]

  for (const c of cookies) {
    const domain = c.domain.startsWith(".") ? c.domain : `.${c.domain}`
    const includeSubdomains = c.domain.startsWith(".") ? "TRUE" : "FALSE"
    const secure = c.secure ? "TRUE" : "FALSE"
    const expiry = c.expires ? Math.floor(c.expires) : 0
    const httpOnly = c.httpOnly ? "TRUE" : "FALSE"

    lines.push(
      `${domain}\t${includeSubdomains}\t${c.path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`,
    )
  }

  return lines.join("\n") + "\n"
}

async function extractCookies(headless = false) {
  const context = await chromium.launchPersistentContext(BROWSER_PROFILE, {
    headless,
    args: [
      "--disable-blink-features=AutomationControlled",
      "--no-sandbox",
      "--disable-setuid-sandbox",
    ],
  })

  try {
    const page = await context.newPage()
    await page.goto("https://www.youtube.com", { waitUntil: "domcontentloaded", timeout: 30000 })

    // Wait a bit for any redirects or consent dialogs
    await page.waitForTimeout(3000)

    // Check if we're logged in
    const isLoggedIn = await page.evaluate(() => {
      // Look for avatar button (logged in indicator)
      const avatar = document.querySelector("yt-img-shadow#avatar")
      return !!avatar
    })

    if (!isLoggedIn) {
      console.warn("Warning: No active YouTube session detected in browser profile")
    }

    // Extract cookies
    const cookies = await context.cookies()
    const ytCookies = cookies.filter((c) =>
      c.domain.includes("youtube.com") ||
      c.domain.includes(".google.com") ||
      c.domain.includes(".youtube.com"),
    )

    if (ytCookies.length === 0) {
      throw new Error("No YouTube cookies found in browser profile")
    }

    // Write to file
    const netscapeContent = cookiesToNetscape(ytCookies)
    fs.writeFileSync(COOKIE_FILE, netscapeContent, { mode: 0o600 })

    console.log(`Extracted ${ytCookies.length} YouTube cookies to ${COOKIE_FILE}`)

    return {
      success: true,
      cookieCount: ytCookies.length,
      cookieNames: ytCookies.map((c) => c.name),
      isLoggedIn,
      timestamp: new Date().toISOString(),
    }
  } finally {
    await context.close()
  }
}

// ─── Routes ───

app.get("/health", (req, res) => {
  const cookieExists = fs.existsSync(COOKIE_FILE)
  let cookieInfo = null

  if (cookieExists) {
    const content = fs.readFileSync(COOKIE_FILE, "utf-8")
    const lines = content.split("\n").filter((l) => l.trim() && !l.startsWith("#"))
    cookieInfo = {
      exists: true,
      lineCount: lines.length,
      lastModified: fs.statSync(COOKIE_FILE).mtime.toISOString(),
      sizeBytes: content.length,
    }
  }

  res.json({
    status: "ok",
    profile: BROWSER_PROFILE,
    cookieFile: COOKIE_FILE,
    cookies: cookieInfo || { exists: false },
  })
})

app.get("/status", (req, res) => {
  const cookieExists = fs.existsSync(COOKIE_FILE)
  const profileExists = fs.existsSync(BROWSER_PROFILE)

  res.json({
    profile: {
      exists: profileExists,
      path: BROWSER_PROFILE,
    },
    cookies: {
      exists: cookieExists,
      path: COOKIE_FILE,
      ...(cookieExists && {
        lastModified: fs.statSync(COOKIE_FILE).mtime.toISOString(),
        sizeBytes: fs.statSync(COOKIE_FILE).size,
      }),
    },
    vnc: {
      available: !!xvfb,
      url: `http://localhost:${VNC_PORT}/vnc.html?autoconnect=true`,
    },
  })
})

// Setup: start VNC for manual login
app.post("/setup", async (req, res) => {
  try {
    if (xvfb) {
      return res.json({ message: "VNC already running", url: `http://localhost:${VNC_PORT}/vnc.html?autoconnect=true` })
    }

    await startVNC()

    // Launch browser in visible mode (headless=false) on the virtual display
    const context = await chromium.launchPersistentContext(BROWSER_PROFILE, {
      headless: false,
      args: [
        "--disable-blink-features=AutomationControlled",
        "--no-sandbox",
        "--disable-setuid-sandbox",
      ],
      env: { ...process.env, DISPLAY: ":99" },
    })

    const page = await context.newPage()
    await page.goto("https://accounts.google.com", { waitUntil: "domcontentloaded" })

    // Auto-extract cookies when browser closes
    context.on("close", async () => {
      console.log("Browser closed, extracting cookies...")
      try {
        const result = await extractCookies(false)
        console.log("Cookie extraction result:", result)
      } catch (err) {
        console.error("Failed to extract cookies after setup:", err.message)
      }
      stopVNC()
    })

    res.json({
      message: "VNC started. Open the URL to login to YouTube.",
      url: `http://localhost:${VNC_PORT}/vnc.html?autoconnect=true`,
      instructions: "Navigate to youtube.com, login, then close the browser to save cookies.",
    })
  } catch (err) {
    stopVNC()
    res.status(500).json({ error: err.message })
  }
})

// Stop VNC session
app.post("/setup/stop", async (req, res) => {
  stopVNC()
  res.json({ message: "VNC stopped" })
})

// Refresh: extract cookies from existing profile (headless, no VNC needed)
app.post("/refresh", async (req, res) => {
  try {
    const result = await extractCookies(true)
    res.json(result)
  } catch (err) {
    res.status(500).json({ error: err.message })
  }
})

// Force login: open browser for manual login (same as setup but without VNC if already running)
app.post("/login", async (req, res) => {
  try {
    const context = await chromium.launchPersistentContext(BROWSER_PROFILE, {
      headless: false,
      args: [
        "--disable-blink-features=AutomationControlled",
        "--no-sandbox",
        "--disable-setuid-sandbox",
      ],
      env: { ...process.env, DISPLAY: ":99" },
    })

    const page = await context.newPage()
    await page.goto("https://accounts.google.com", { waitUntil: "domcontentloaded" })

    context.on("close", async () => {
      console.log("Browser closed after login, extracting cookies...")
      try {
        await extractCookies(false)
      } catch (err) {
        console.error("Failed to extract cookies:", err.message)
      }
    })

    res.json({ message: "Browser opened for login. Close it when done." })
  } catch (err) {
    res.status(500).json({ error: err.message })
  }
})

// Start server
app.listen(PORT, () => {
  console.log(`Cookie refresher running on port ${PORT}`)
  console.log(`Profile: ${BROWSER_PROFILE}`)
  console.log(`Cookie file: ${COOKIE_FILE}`)
})
